<center>
<img width="150px" src="./images/Logo_EasternCyber_2017_300x140.png">
<h1>Eastern Cyber Co., Ltd.</h1>
</center>
<p>
<hr><br>
<h3>Website</h3>
<p>Almost 30 years of experiences, we design and create websites for many people and organizations 
<b>Simple , Fast and Easy to Manage</b> are the successful concepts of powerful website.</p>
<h3>Social Network</h3>
<p>If you want to have your own facebook-like platform social network, let we create it for you.</p>
<p>
<h3>Social Intranet & Knowledge base</h3>
<p>Social Intranet can identify as the internal social network inside a particular organization which could help to collaborate your team.</p>
<p>
<h3>Blockchain & Crypto Token</h3>
<p>In this era, one of the most popular disruptive technology is Blockchain and Crypto Currencies/Tokens. 
We are proud to present to you the most advanced technology to build BitCoin like Crypto Token own by you.</p>
